info:
  component: test Template

server:
  port: 10000
 

# Logbook 
logbook:
    filter.enabled: true
    format.style: http
    obfuscate:
        headers:
            - Authorization
            - X-Secret
        parameters:
            - access_token
            - password
    write:
        category: http.wire-log
        level: WARN
        chunk-size: 1000